# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
