# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronitor', '0002_auto_20160423_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='auth_token',
            field=models.TextField(db_index=True, unique=True),
        ),
    ]
