# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronitor', '0003_auto_20160424_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='is_up',
            field=models.BooleanField(default=True),
        ),
    ]
