# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronitor', '0004_log_is_up'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='log',
            name='ip_address',
            field=models.GenericIPAddressField(default=b'127.0.0.1'),
        ),
    ]
