# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronitor', '0007_auto_20160424_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='interval',
            field=models.IntegerField(default=1, verbose_name=b'Interval in minutes'),
        ),
    ]
